author: Femonzor

theme: typing

deploy:
  type: git
  repo: git@github.com:Femonzor/femonzor.github.io.git
  branch: master

donate: false

archive_generator:
  per_page: 15
  yearly: true
  monthly: true

language: zh-CN

highlight:
  enable: false
  line_number: false
  auto_detect: false
  tab_replace:
