author: Femonzor
title: Femonzor's Blog

theme: typing

deploy:
  type: git
  repo: git@github.com:Femonzor/femonzor.github.io.git
  branch: master

donate: false

archive_generator:
  per_page: 15
  yearly: true
  monthly: true

language: zh-CN

highlight:
  enable: false
  line_number: false
  auto_detect: false
  tab_replace:

toc:
  list_number: true
  max_depth: 2

post_asset_folder: true

# asset_pipeline:
#   revisioning:
#     enable: true
